# Scitech data import from Dimensions
## Matching operation
 Made by: Dr. Keungoui Kim

In [1]:
### Library
import pandas as pd
import numpy as np
import math

### Directory Setting for Export
#dir = "E:/Google Drive (awekim@handong.edu)/[Research]/00_Dimensions/Dimension_files/" # Home
dir = "D:/Google Drive(awekim@handong.edu)/[Research]/00_Dimensions/Dimension_files/" # HGU

In [ ]:
### API log in
import dimcli
dimcli.login(key="792DDFAFCCA7478D8F37159F274A2783",
             endpoint="https://app.dimensions.ai/api/dsl/v2")

dsl = dimcli.Dsl()

In [ ]:
#years = ['2000','2001','2002','2003','2004','2005','2006','2007','2008','2009'] #'2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022'
#offices = ['EP'] # 'WO', 'US', 'EP'

In [24]:
year='2020'
office='EP'
i = 1

pat_df = pd.read_csv(dir+"pat_data_df_"+year+"_"+office+".csv")
pat_pub_df = pd.read_csv(dir+"pat_pub_df_"+year+"_"+office+".csv")
pub_list = pd.read_csv(dir+"pub_list_df_"+year+"_"+office+str(i)+".csv")
pub_df = pd.read_csv(dir+"pub_data_df_"+year+"_"+office+"_"+str(i)+".csv")

In [9]:
pat_df.head()

,id,cpc,family_id,jurisdiction,priority_date,priority_year,publication_ids
0,EP-4072192-A1,"['H04W36/0058', 'H04W28/0808', 'H04B17/382', '...",79185558,EP,2020-12-31,2020,['pub.1121662354']
1,EP-4024810-A1,"['H04L63/0807', 'H04L9/50', 'H04L9/3239', 'H04...",74494747,EP,2020-12-31,2020,['pub.1121932616']
2,EP-4024726-A1,"['H04B7/18517', 'H04B7/18521', 'H04W84/18', 'H...",79024682,EP,2020-12-31,2020,['pub.1094947680']
3,EP-4024725-A1,"['H04B7/024', 'H04W84/18', 'H04B7/026', 'H04L1...",79024904,EP,2020-12-31,2020,['pub.1095139837']
4,EP-4024695-A1,"['F05B2270/342', 'H02P2101/15', 'F03D9/257', '...",79024308,EP,2020-12-31,2020,['pub.1105931095']

In [25]:
pat_pub_df.head()

              id publication_ids
0  EP-4072192-A1  pub.1121662354
1  EP-4024810-A1  pub.1121932616
2  EP-4024726-A1  pub.1094947680
3  EP-4024725-A1  pub.1095139837
4  EP-4024695-A1  pub.1105931095

In [26]:
pub_df.head()

,id,title,authors,category_for,type,year,journal.id,journal.title,volume,issue
0,pub.1146776198,Generative Adversarial Networks for face gener...,"[{'affiliations': [{'city': 'Sfax', 'city_id':...","[{'id': '80017', 'name': '46 Information and C...",article,2022,jour.1119907,ACM Computing Surveys,NaN,NaN
1,pub.1144826596,Embedding Normalization: Significance Preservi...,"[{'affiliations': [{'city': None, 'city_id': N...","[{'id': '80017', 'name': '46 Information and C...",proceeding,2021,NaN,NaN,00,NaN
2,pub.1140779235,Mineral Processing and Metal Extraction on the...,"[{'affiliations': [{'city': 'Melbourne', 'city...","[{'id': '80011', 'name': '40 Engineering'}, {'...",article,2021,jour.1139651,Mineral Processing and Extractive Metallurgy R...,43,7
3,pub.1137477177,NH2 linker for femtomolar label-free detection...,"[{'affiliations': [{'city': 'Plymouth', 'city_...","[{'id': '80065', 'name': '3401 Analytical Chem...",article,2021,jour.1033315,Carbon,179,NaN
4,pub.1139149037,Engineering the Surface Pattern of Micropartic...,"[{'affiliations': [{'city': 'Chengdu', 'city_i...","[{'id': '80005', 'name': '34 Chemical Sciences...",article,2021,jour.1041450,ACS Applied Materials & Interfaces,13,26

In [30]:
pub_df[pub_df['id']=='pub.1121932616']

,id,title,authors,category_for,type,year,journal.id,journal.title,volume,issue
82,pub.1121932616,GDPR-Compliant Personal Data Management: A Blo...,"[{'affiliations': [{'city': 'London', 'city_id...","[{'id': '80017', 'name': '46 Information and C...",article,2019,jour.1137734,IEEE Transactions on Information Forensics and...,15,NaN